/* Copyright 2022 Shaun Brandt

   Permission is hereby granted, free of charge, to any person obtaining a
   copy of this software and associated documentation files (the "Software"),
   to deal in the Software without restriction, including without limitation
   the rights to use, copy, modify, merge, publish, distribute, sublicense,
   and/or sell copies of the Software, and to permit persons to whom the
   Software is furnished to do so, subject to the following conditions:

   The above copyright notice and this permission notice shall be included
   in all copies or substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
   FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
   DEALINGS IN THE SOFTWARE.
 */
#include "../INCLUDE/DDUNIDLE.H"

int g_num_masteries;
int g_num_skills;
int g_active_skill;

float g_action_progress;
float g_mastery_progress;
float g_skill_progress;

void process_proc(Skill *s) {
    // If the mastery has procced
    //  - Give the player the item generated by the skill that just procced
    //  - increase the mastery exp
    //  - If mastery exp is enough for the next level 
    //    - Increase mastery level
    //  - Increase the skill exp by the amount from the particular mastery
    //  - If skill exp is enough for the next level
    //    - Increase skill level
    //  - reset the proc counter
    Mastery *m = get_active_mastery(s);

    if (!s->is_currently_active) {
        printf("Current skill is inactive!\n");
        return;
    }

    // Update the action progress percentage (for the progress bar)
    g_action_progress = get_action_progress(m->execution_time, g_skill_timer, m->next_proc);
    
    if (g_skill_timer >= m->next_proc) {
        m->current_exp++;
        // Attempt to add the item to the player's inventory (if room exists)
        add_item_to_inventory(m->product_item_id);
        // Update the mastery progress percentage (for progress bar)
        g_mastery_progress = get_mastery_progress(m->current_exp, m->current_level);
        // Update the mastery level if necessary
        if(m->current_level < 100 && m->current_exp >= g_mastery_exp_table[m->current_level]) {
                m->current_level++;
                printf("Mastery %s level increased to %d\n", m->name, m->current_level);
        }
        s->current_exp += m->skill_exp;
        g_skill_progress = get_skill_progress(s->current_exp, s->current_level);
        printf("Skill progress = %.2f\n", g_skill_progress);
        // Update the skill level if necessary
        if(s->current_level < 100 && s->current_exp >= g_skill_exp_table[s->current_level]) {
                s->current_level++;
                printf("%s skill level increased to %d\n", s->name, s->current_level);
        }
        set_next_proc(m);
    }
}

Skill *get_active_skill(void) {
    return &(g_skill_list[g_active_skill]);
}

Mastery *get_active_mastery(Skill *s) {
    return &(g_mastery_list[s->active_mastery]);
}

void set_active_mastery(Skill *s, int mastery_id) {
    s->active_mastery = mastery_id;
}

void activate_skill(Skill *s) {
    s->is_currently_active = 1;
    set_next_proc(get_active_mastery(s));
}

void deactivate_skill (Skill *s) {
    s->is_currently_active = 0;
}

void set_next_proc(Mastery *m) {
    m->next_proc = g_skill_timer + m->execution_time;
}

char *get_skill_name(Skill *s) {
    return s->name;
}

char *get_mastery_name(Mastery *m) {
    return m->name;
}

void debug_skill(Skill *s) {
    int i;

    for(i=0; i<s->num_masteries; i++) {
        printf("Mastery %d\n", (i+1));
        if(s->active_mastery == i) {
            printf("  * This mastery is the active one! *\n");
        }

        printf("  - Current level: %d\n", g_mastery_list[s->masteries[i]].current_level);
        printf("  - current exp: %d\n", g_mastery_list[s->masteries[i]].current_exp);
        printf("  - time per action: %d\n", g_mastery_list[s->masteries[i]].execution_time);
    }

    if(s->is_currently_active) {
        printf("This skill is currently being worked on!\n");
    }
    else {
        printf("This skill is NOT currently being worked on!\n");
    }
}

// Calculates how far along the current action we are
float get_action_progress(unsigned int execution_time, unsigned int timer, unsigned int proc) {
    unsigned int start_time = proc - execution_time;
    unsigned int progress = timer - start_time;
    return (float)((float)progress/execution_time);
}

// Calculates how far along the mastery we are.  
// This is defined as the percentage of the way from the start of the current mastery level to the 
// previous level
//
// Example:
// For coal, assume we're level 8 with 31 experience.  Level 9 requires 36 experience, with a 
// experience delta of 7.  The previous level required 29 experience, so we have 2 out of 7 experience
// required for the next level. 
//
// We need to know the current level and the current experience
// Note that the current mastery level is mastery_level - 1
float get_mastery_progress(unsigned int cur_exp, unsigned int mastery_level) {
    int progress_exp = cur_exp - g_mastery_exp_table[mastery_level-1];
    int req_exp = g_mastery_exp_to_level_table[mastery_level];
    return (float)((float)progress_exp/req_exp);
}

float get_skill_progress(unsigned int cur_exp, unsigned int skill_level) {
    float progress;
    int progress_exp = cur_exp - g_skill_exp_table[skill_level-1];
    int req_exp = g_skill_exp_to_level_table[skill_level];
    progress = (float)((float)progress_exp/req_exp);
    if (progress > 1.0f) {
        progress = 1.0f;
    } 
    return progress;
}